import puppeteer from 'puppeteer';

interface Account {
  id: number;
  code: string;
  name: string;
  nameAr: string | null;
  type: string;
  balance: string;
}

interface CashFlow {
  type: string;
  category: string;
  description: string | null;
  amount: string;
  date: string;
}

interface ReportData {
  orgName: string;
  year: number;
  lang: 'ar' | 'en';
  accounts: Account[];
  cashFlows: CashFlow[];
}

function formatAmount(amount: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 2
  }).format(amount);
}

function generateReportHTML(data: ReportData): string {
  const { orgName, year, lang, accounts, cashFlows } = data;
  const isRTL = lang === 'ar';
  const dir = isRTL ? 'rtl' : 'ltr';
  const textAlign = isRTL ? 'right' : 'left';
  const numAlign = isRTL ? 'left' : 'right';
  
  const currentDate = new Date().toLocaleDateString(isRTL ? 'ar-SA' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const assets = accounts.filter(a => a.type === 'asset');
  const liabilities = accounts.filter(a => a.type === 'liability');
  const equity = accounts.filter(a => a.type === 'equity');
  const revenue = accounts.filter(a => a.type === 'revenue');
  const expenses = accounts.filter(a => a.type === 'expense');

  const totalAssets = assets.reduce((sum, a) => sum + parseFloat(a.balance || '0'), 0);
  const totalLiabilities = liabilities.reduce((sum, a) => sum + parseFloat(a.balance || '0'), 0);
  const totalEquity = equity.reduce((sum, a) => sum + parseFloat(a.balance || '0'), 0);
  const totalRevenue = revenue.reduce((sum, a) => sum + parseFloat(a.balance || '0'), 0);
  const totalExpenses = expenses.reduce((sum, a) => sum + parseFloat(a.balance || '0'), 0);
  const netIncome = totalRevenue - totalExpenses;

  const operatingCF = cashFlows.filter(cf => cf.type === 'operating').reduce((sum, cf) => sum + parseFloat(cf.amount || '0'), 0);
  const investingCF = cashFlows.filter(cf => cf.type === 'investing').reduce((sum, cf) => sum + parseFloat(cf.amount || '0'), 0);
  const financingCF = cashFlows.filter(cf => cf.type === 'financing').reduce((sum, cf) => sum + parseFloat(cf.amount || '0'), 0);
  const netCashFlow = operatingCF + investingCF + financingCF;

  const t = {
    balanceSheet: isRTL ? 'الميزانية العمومية' : 'Balance Sheet',
    incomeStatement: isRTL ? 'قائمة الدخل' : 'Income Statement',
    cashFlowStatement: isRTL ? 'قائمة التدفقات النقدية' : 'Cash Flow Statement',
    code: isRTL ? 'الكود' : 'Code',
    accountName: isRTL ? 'اسم الحساب' : 'Account Name',
    balance: isRTL ? 'الرصيد' : 'Balance',
    assets: isRTL ? 'الأصول' : 'Assets',
    liabilities: isRTL ? 'الالتزامات' : 'Liabilities',
    equity: isRTL ? 'حقوق الملكية' : 'Equity',
    totalAssets: isRTL ? 'إجمالي الأصول' : 'Total Assets',
    totalLiabilities: isRTL ? 'إجمالي الالتزامات' : 'Total Liabilities',
    totalEquity: isRTL ? 'إجمالي حقوق الملكية' : 'Total Equity',
    totalLiabilitiesEquity: isRTL ? 'إجمالي الالتزامات وحقوق الملكية' : 'Total Liabilities & Equity',
    balanced: isRTL ? 'الميزانية متوازنة' : 'Balance Sheet is Balanced',
    notBalanced: isRTL ? 'الميزانية غير متوازنة' : 'Balance Sheet is NOT Balanced',
    revenue: isRTL ? 'الإيرادات' : 'Revenue',
    expenses: isRTL ? 'المصروفات' : 'Expenses',
    totalRevenue: isRTL ? 'إجمالي الإيرادات' : 'Total Revenue',
    totalExpenses: isRTL ? 'إجمالي المصروفات' : 'Total Expenses',
    netIncome: isRTL ? 'صافي الدخل' : 'Net Income',
    profitMargin: isRTL ? 'هامش الربح' : 'Profit Margin',
    expenseRatio: isRTL ? 'نسبة المصروفات' : 'Expense Ratio',
    item: isRTL ? 'البند' : 'Item',
    amount: isRTL ? 'المبلغ' : 'Amount',
    operating: isRTL ? 'الأنشطة التشغيلية' : 'Operating Activities',
    investing: isRTL ? 'الأنشطة الاستثمارية' : 'Investing Activities',
    financing: isRTL ? 'الأنشطة التمويلية' : 'Financing Activities',
    netCashFlow: isRTL ? 'صافي التدفق النقدي' : 'Net Cash Flow',
    fiscalYear: isRTL ? 'السنة المالية' : 'Fiscal Year',
    reportDate: isRTL ? 'تاريخ التقرير' : 'Report Date',
    forYear: isRTL ? `للسنة المالية المنتهية في 31 ديسمبر ${year}` : `For the Year Ended December 31, ${year}`,
    generatedBy: isRTL ? 'تم إنشاء هذا التقرير بواسطة' : 'Generated by'
  };

  const getName = (acc: Account) => isRTL && acc.nameAr ? acc.nameAr : acc.name;

  const renderAccountRows = (accs: Account[]) => accs.map(acc => `
    <tr>
      <td style="padding: 10px 12px; border-bottom: 1px solid #e5e7eb; font-family: monospace; font-size: 12px;">${acc.code}</td>
      <td style="padding: 10px 12px; border-bottom: 1px solid #e5e7eb;">${getName(acc)}</td>
      <td style="padding: 10px 12px; border-bottom: 1px solid #e5e7eb; text-align: ${numAlign}; font-family: 'Courier New', monospace;">${formatAmount(parseFloat(acc.balance || '0'))}</td>
    </tr>
  `).join('');

  return `
<!DOCTYPE html>
<html lang="${lang}" dir="${dir}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>INFERA Financial Report</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400;500;600;700&family=Inter:wght@400;500;600;700&display=swap');
    
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: ${isRTL ? "'Noto Naskh Arabic', 'Segoe UI', Tahoma, sans-serif" : "'Inter', 'Segoe UI', Arial, sans-serif"};
      font-size: 13px;
      line-height: 1.6;
      color: #1a1a1a;
      background: white;
      direction: ${dir};
      text-align: ${textAlign};
    }
    
    .page {
      padding: 30px 40px;
      max-width: 210mm;
      margin: 0 auto;
    }
    
    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-bottom: 3px solid #0891b2;
      padding-bottom: 20px;
      margin-bottom: 30px;
      flex-direction: ${isRTL ? 'row-reverse' : 'row'};
    }
    
    .header-left {
      text-align: ${textAlign};
    }
    
    .header-right {
      text-align: ${isRTL ? 'left' : 'right'};
    }
    
    .logo {
      font-size: 22px;
      font-weight: 700;
      color: #0891b2;
      margin-bottom: 4px;
    }
    
    .org-name {
      font-size: 14px;
      color: #666;
    }
    
    .report-info {
      font-size: 12px;
      color: #888;
    }
    
    .report-info strong {
      display: block;
      font-size: 14px;
      color: #333;
      margin-top: 2px;
    }
    
    .section {
      margin-bottom: 40px;
    }
    
    .section-title {
      font-size: 18px;
      font-weight: 700;
      color: #1a1a1a;
      border-bottom: 2px solid #e5e7eb;
      padding-bottom: 10px;
      margin-bottom: 20px;
    }
    
    .section-subtitle {
      font-size: 13px;
      color: #666;
      margin-bottom: 15px;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 20px;
    }
    
    th {
      background: #f3f4f6;
      padding: 12px;
      text-align: ${textAlign};
      font-weight: 600;
      border-bottom: 2px solid #d1d5db;
      font-size: 12px;
    }
    
    th:last-child {
      text-align: ${numAlign};
    }
    
    .category-row {
      background: #f9fafb;
    }
    
    .category-row td {
      padding: 12px;
      font-weight: 700;
      color: #059669;
    }
    
    .category-row.liabilities td { color: #dc2626; }
    .category-row.equity td { color: #2563eb; }
    .category-row.revenue td { color: #059669; }
    .category-row.expenses td { color: #dc2626; }
    
    .subtotal-row {
      background: #d1fae5;
    }
    
    .subtotal-row.liabilities { background: #fee2e2; }
    .subtotal-row.equity { background: #dbeafe; }
    .subtotal-row.revenue { background: #d1fae5; }
    .subtotal-row.expenses { background: #fee2e2; }
    
    .subtotal-row td {
      padding: 12px;
      font-weight: 700;
    }
    
    .total-row {
      background: #cffafe;
      border-top: 3px solid #0891b2;
    }
    
    .total-row td {
      padding: 14px 12px;
      font-weight: 700;
      font-size: 14px;
    }
    
    .positive { color: #059669; }
    .negative { color: #dc2626; }
    
    .balance-status {
      padding: 14px;
      border-radius: 6px;
      font-weight: 600;
      margin-top: 15px;
    }
    
    .balance-status.balanced {
      background: #d1fae5;
      color: #065f46;
    }
    
    .balance-status.not-balanced {
      background: #fee2e2;
      color: #991b1b;
    }
    
    .metrics-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 20px;
      margin-top: 20px;
    }
    
    .metric-card {
      padding: 16px;
      background: #f3f4f6;
      border-radius: 8px;
    }
    
    .metric-label {
      font-size: 12px;
      color: #666;
      margin-bottom: 4px;
    }
    
    .metric-value {
      font-size: 22px;
      font-weight: 700;
    }
    
    .metric-value.primary { color: #0891b2; }
    .metric-value.warning { color: #d97706; }
    
    .cf-summary {
      display: flex;
      flex-direction: column;
      gap: 12px;
      margin-bottom: 24px;
    }
    
    .cf-item {
      display: flex;
      justify-content: space-between;
      padding: 14px 16px;
      border-radius: 6px;
      flex-direction: ${isRTL ? 'row-reverse' : 'row'};
    }
    
    .cf-item.operating { background: #dbeafe; }
    .cf-item.investing { background: #ede9fe; }
    .cf-item.financing { background: #fef3c7; }
    
    .cf-item span:first-child {
      font-weight: 500;
    }
    
    .cf-item span:last-child {
      font-weight: 700;
      font-family: 'Courier New', monospace;
    }
    
    .cf-total {
      display: flex;
      justify-content: space-between;
      padding: 16px;
      border-radius: 6px;
      font-weight: 700;
      font-size: 15px;
      border-top: 3px solid #0891b2;
      background: #cffafe;
      flex-direction: ${isRTL ? 'row-reverse' : 'row'};
    }
    
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      font-size: 11px;
      color: #888;
    }
    
    .page-break {
      page-break-before: always;
    }
  </style>
</head>
<body>
  <div class="page">
    <header class="header">
      <div class="header-left">
        <div class="logo">INFERA Finance AI GlobalCloud</div>
        <div class="org-name">${orgName}</div>
      </div>
      <div class="header-right">
        <div class="report-info">${t.reportDate}<strong>${currentDate}</strong></div>
        <div class="report-info" style="margin-top: 8px;">${t.fiscalYear}<strong>${year}</strong></div>
      </div>
    </header>

    <section class="section">
      <h2 class="section-title">${t.balanceSheet}</h2>
      <table>
        <thead>
          <tr>
            <th style="width: 15%;">${t.code}</th>
            <th style="width: 55%;">${t.accountName}</th>
            <th style="width: 30%;">${t.balance}</th>
          </tr>
        </thead>
        <tbody>
          <tr class="category-row">
            <td colspan="3">${t.assets}</td>
          </tr>
          ${renderAccountRows(assets)}
          <tr class="subtotal-row">
            <td colspan="2">${t.totalAssets}</td>
            <td style="text-align: ${numAlign}; font-family: 'Courier New', monospace;" class="positive">${formatAmount(totalAssets)}</td>
          </tr>
          
          <tr class="category-row liabilities">
            <td colspan="3" style="padding-top: 20px;">${t.liabilities}</td>
          </tr>
          ${renderAccountRows(liabilities)}
          <tr class="subtotal-row liabilities">
            <td colspan="2">${t.totalLiabilities}</td>
            <td style="text-align: ${numAlign}; font-family: 'Courier New', monospace;" class="negative">${formatAmount(totalLiabilities)}</td>
          </tr>
          
          <tr class="category-row equity">
            <td colspan="3" style="padding-top: 20px;">${t.equity}</td>
          </tr>
          ${renderAccountRows(equity)}
          <tr class="subtotal-row equity">
            <td colspan="2">${t.totalEquity}</td>
            <td style="text-align: ${numAlign}; font-family: 'Courier New', monospace;">${formatAmount(totalEquity)}</td>
          </tr>
          
          <tr class="total-row">
            <td colspan="2">${t.totalLiabilitiesEquity}</td>
            <td style="text-align: ${numAlign}; font-family: 'Courier New', monospace;">${formatAmount(totalLiabilities + totalEquity)}</td>
          </tr>
        </tbody>
      </table>
      <div class="balance-status ${Math.abs(totalAssets - (totalLiabilities + totalEquity)) < 0.01 ? 'balanced' : 'not-balanced'}">
        ${Math.abs(totalAssets - (totalLiabilities + totalEquity)) < 0.01 ? '✓ ' + t.balanced : '✗ ' + t.notBalanced}
      </div>
    </section>

    <div class="page-break"></div>

    <section class="section">
      <h2 class="section-title">${t.incomeStatement}</h2>
      <p class="section-subtitle">${t.forYear}</p>
      <table>
        <thead>
          <tr>
            <th style="width: 15%;">${t.code}</th>
            <th style="width: 55%;">${t.item}</th>
            <th style="width: 30%;">${t.amount}</th>
          </tr>
        </thead>
        <tbody>
          <tr class="category-row revenue">
            <td colspan="3">${t.revenue}</td>
          </tr>
          ${renderAccountRows(revenue)}
          <tr class="subtotal-row revenue">
            <td colspan="2">${t.totalRevenue}</td>
            <td style="text-align: ${numAlign}; font-family: 'Courier New', monospace;" class="positive">${formatAmount(totalRevenue)}</td>
          </tr>
          
          <tr class="category-row expenses">
            <td colspan="3" style="padding-top: 20px;">${t.expenses}</td>
          </tr>
          ${renderAccountRows(expenses)}
          <tr class="subtotal-row expenses">
            <td colspan="2">${t.totalExpenses}</td>
            <td style="text-align: ${numAlign}; font-family: 'Courier New', monospace;" class="negative">${formatAmount(totalExpenses)}</td>
          </tr>
          
          <tr class="total-row" style="background: ${netIncome >= 0 ? '#d1fae5' : '#fee2e2'}; border-color: ${netIncome >= 0 ? '#059669' : '#dc2626'};">
            <td colspan="2">${t.netIncome}</td>
            <td style="text-align: ${numAlign}; font-family: 'Courier New', monospace;" class="${netIncome >= 0 ? 'positive' : 'negative'}">${formatAmount(netIncome)}</td>
          </tr>
        </tbody>
      </table>
      
      <div class="metrics-grid">
        <div class="metric-card">
          <div class="metric-label">${t.profitMargin}</div>
          <div class="metric-value primary">${totalRevenue > 0 ? ((netIncome / totalRevenue) * 100).toFixed(1) : 0}%</div>
        </div>
        <div class="metric-card">
          <div class="metric-label">${t.expenseRatio}</div>
          <div class="metric-value warning">${totalRevenue > 0 ? ((totalExpenses / totalRevenue) * 100).toFixed(1) : 0}%</div>
        </div>
      </div>
    </section>

    <div class="page-break"></div>

    <section class="section">
      <h2 class="section-title">${t.cashFlowStatement}</h2>
      <p class="section-subtitle">${t.fiscalYear} ${year}</p>
      
      <div class="cf-summary">
        <div class="cf-item operating">
          <span>${t.operating}</span>
          <span class="${operatingCF >= 0 ? 'positive' : 'negative'}">${formatAmount(operatingCF)}</span>
        </div>
        <div class="cf-item investing">
          <span>${t.investing}</span>
          <span class="${investingCF >= 0 ? 'positive' : 'negative'}">${formatAmount(investingCF)}</span>
        </div>
        <div class="cf-item financing">
          <span>${t.financing}</span>
          <span class="${financingCF >= 0 ? 'positive' : 'negative'}">${formatAmount(financingCF)}</span>
        </div>
      </div>
      
      <div class="cf-total" style="background: ${netCashFlow >= 0 ? '#d1fae5' : '#fee2e2'}; border-color: ${netCashFlow >= 0 ? '#059669' : '#dc2626'};">
        <span>${t.netCashFlow}</span>
        <span class="${netCashFlow >= 0 ? 'positive' : 'negative'}">${formatAmount(netCashFlow)}</span>
      </div>
    </section>

    <footer class="footer">
      <p>${t.generatedBy} INFERA Finance AI GlobalCloud</p>
      <p>${currentDate}</p>
    </footer>
  </div>
</body>
</html>
`;
}

export async function generatePDF(data: ReportData): Promise<Buffer> {
  const html = generateReportHTML(data);
  
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage']
  });
  
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '10mm',
        right: '10mm',
        bottom: '10mm',
        left: '10mm'
      }
    });
    
    return Buffer.from(pdfBuffer);
  } finally {
    await browser.close();
  }
}
